#!/bin/bash

filePath=$1

usage()
{
  echo "Usage: $0 [ file path ] [ -d date ] "
}

shift

while getopts ":d:" opt
   do
     case $opt in
        d) date=$OPTARG;;
        *) usage;;
     esac
done

if [ -z "$filePath" ] ; then
   echo 'Please supply input cookie csv file name'
   usage  
   exit 1
fi

if [ -z "$date" ] ; then
   echo 'Please supply search date i.e -d yyyy-mm-dd'
   usage 
   exit 1 
fi
python cookie/hot_cookie.py $filePath $date
